# pylint: disable=unused-argument

from typing import Any

class Pretty:
    def __init__(self, indent: int = 4) -> None: ...
    @property
    def indent(self) -> int: ...
    @indent.setter
    def indent(self, value: int) -> None: ...
    def print(self, obj: Any) -> None: ...
